name: Sync upstream
# This runs every day on 1000 UTC
on:
  schedule:
    - cron: '0 10 * * *'
  # Allows manual workflow run
  workflow_dispatch:

permissions: write-all

jobs:
 build:
  runs-on: ubuntu-latest
  permissions:
    id-token: write
  steps:
    - name: Debug OIDC Claims
      uses: github/actions-oidc-debugger@main
      with:
        audience: "octo-debugger"
    - name: Create upstream version tag
      uses: DataDog/sync-upstream-release-tag@main
      with:
        github_actor: "${GITHUB_ACTOR}"
        github_repository: "${GITHUB_REPOSITORY}"
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upstream_repo: kubernetes-csi/livenessprobe
